package com.makhalibagas.moviesaja.utils

import com.makhalibagas.moviesaja.R
import com.makhalibagas.moviesaja.data.MoviesAja

object DataDummy {

    fun moviesAjaList() = listOf(
            MoviesAja(1,
                    "The Falcon and the Winter Soldier (2021)",
                    "Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.",
                    R.drawable.poster02,
                    R.drawable.poster02),
            MoviesAja(2,
                    "Avengers: Infinity War (2018)",
                    "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
                    R.drawable.poster01,
                    R.drawable.poster01),
            MoviesAja(3,
                    "Avengers: Endgame (2019)",
                    "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
                    R.drawable.poster03,
                    R.drawable.poster03),
            MoviesAja(4,
            "Mortal Kombat (2021)",
                    "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
                    R.drawable.poster04,
                    R.drawable.poster04),
            MoviesAja(5,
                    "Godzilla vs. Kong (2021)",
                    "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
                    R.drawable.poster05,
                    R.drawable.poster05),
            MoviesAja(6,
                    "Vanquish (2021)",
                    "Victoria is a young mother trying to put her dark past as a Russian drug courier behind her, but retired cop Damon forces Victoria to do his bidding by holding her daughter hostage. Now, Victoria must use guns, guts and a motorcycle to take out a series of violent gangsters—or she may never see her child again.",
                    R.drawable.poster06,
                    R.drawable.poster06),
            MoviesAja(7,
                    "Nobody (2021)",
                    "Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a \"nobody.\" When two thieves break into his home one night, Hutch's unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.",
                    R.drawable.poster07,
                    R.drawable.poster07),
            MoviesAja(8,
                    "Justice Society: World War II (2021)",
                    "While speeding off to help in an impromptu battle, The Flash blazes and rips through time, only to find himself dropped into the middle of World War II. It’s here that The Flash meets Wonder Woman and her top secret team, known as the Justice Society of America. Amidst the raging tides of war, gripping combat and the velocity of valor, The Flash must fight to return to his own timeline.",
                    R.drawable.poster08,
                    R.drawable.poster08),
            MoviesAja(9,
                    "Skylines (2020)",
                    "When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.",
                    R.drawable.poster09,
                    R.drawable.poster09),
            MoviesAja(10,
                    "Monster Hunter (2020)",
                    "A portal transports Cpt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.",
                    R.drawable.poster10,
                    R.drawable.poster10),

    )

    fun tvShowsAjaList() = listOf(
            MoviesAja(1,
                    "The Flash (2014)",
                    "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.",
                    R.drawable.tv01,
                    R.drawable.tv01),
            MoviesAja(2,
                    "The Good Doctor (2017)",
                    "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives",
                    R.drawable.tv02,
                    R.drawable.tv02),
            MoviesAja(3,
                    "Luis Miguel: The Series (2018)",
                    "The series dramatizes the life story of Mexican superstar singer Luis Miguel, who has captivated audiences in Latin America and beyond for decades.",
                    R.drawable.tv03,
                    R.drawable.tv03),
            MoviesAja(4,
                    "Grey's Anatomy (2005)",
                    "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
                    R.drawable.tv04,
                    R.drawable.tv04),
            MoviesAja(5,
                    "Riverdale (2017)",
                    "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.",
                    R.drawable.tv05,
                    R.drawable.tv05),
            MoviesAja(6,
                    "Lucifer (2016)",
                    "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
                    R.drawable.tv06,
                    R.drawable.tv06),
            MoviesAja(7,
                    "Van Helsing (2016)",
                    "Vanessa Helsing, the daughter of famous vampire hunter and Dracula nemesis Abraham Van Helsing is resurrected five years in the future to find out that vampires have taken over the world and that she possesses unique power over them. She is humanity’s last hope to lead an offensive to take back what has been lost.",
                    R.drawable.tv07,
                    R.drawable.tv07),
            MoviesAja(8,
                    "Haunted: Latin America (2021)",
                    "Real people's terrifying tales of the chilling, unexplained and paranormal come to life with dramatic reenactments in this reality series.",
                    R.drawable.tv08,
                    R.drawable.tv08),
            MoviesAja(9,
                    "Game of Thrones (2011)",
                    "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
                    R.drawable.tv09,
                    R.drawable.tv09),
            MoviesAja(10,
                    "The Walking Dead (2010)",
                    "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
                    R.drawable.tv10,
                    R.drawable.tv10),


    )

}